name: Python Linter

on: [push, pull_request]

jobs:
 format:
   runs-on: windows-latest

   steps:
   - uses: actions/checkout@v3
   
   - name: Install MSYS2
     uses: msys2/setup-msys2@v2
     with:
       update: true
       install: >-
         python
         python-pip
       path-type: inherit

   - name: Install Black
     shell: msys2 {0}
     run: pip install black
     
   - name: Check Python files format
     shell: msys2 {0}
     run: python -m black --check .
